site_name: GRC Alignment Doc
site_description: 'GRC Alignment Doc'
site_author: 'tankerkiller125'
docs_dir: docs
repo_name: 'tankerkiller125/graphgrc'
repo_url: 'https://github.com/tankerkiller125/graphgrc'
nav:
  - SCF: scf/index.md
  - ISO 27001: iso27001/index.md
  - ISO 27002: iso27002/index.md
  - SOC 2: soc2/index.md
theme:
  name: 'material'
